---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: polkadot-private-node-policy
  namespace: default
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: private-node
  policyTypes:
  - Ingress
  - Egress
  egress:
  - ports:
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
    - port: 443
      protocol: TCP
    - port: 30333
      protocol: TCP
    - port: 30334
      protocol: TCP
    - port: 30100
      protocol: TCP
  ingress:
  - ports:
    - port: {{ .Values.p2p_port }}
      protocol: TCP
  - ports:
    - port: 9615
      protocol: TCP
    from:
    - namespaceSelector:
        matchLabels: {}
      podSelector:
        matchLabels:
          app: prometheus
